version: "3.8"

services:
  db:
    image: postgres:13
    container_name: postgres-courses-db
    environment:
      POSTGRES_DB: init_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "54321:5432"
    volumes:
      - postgres_data_courses:/var/lib/postgresql/data

volumes:
  postgres_data_courses: